---
- name: Install ProFTPD
  apt:
    name: proftpd
    state: present 
    update_cache: yes
    cache_valid_time: 3600
- name: mkdir anonymous
  file: 
    path: "{{ PRO_DIR  }}"
    owner: ftp
    group: nogroup
    state: directory 

- name: change usermod
  command: usermod -d {{ PRO_DIR  }} ftp

- name: mkdir virtualusers
  file:
    path: "{{ PRO_VIR_DIR }}"
    owner: "{{ PRO_UID }}"
    group: "{{ PRO_GID }}"
    mode: "{{PRO_LIMIT}}" 
    state: directory

- name: mkdir /usr/local/etc/proftpd
  file:
    path: /usr/local/etc/proftpd
    state: directory

- name: ftpasswd user
  shell: echo "{{ PRO_VIRTUAL_PASS }}"|ftpasswd --passwd --file=/usr/local/etc/proftpd/passwd --name="{{ PRO_VIRTUAL_USER }}" --uid="{{ PRO_UID }}" --home="{{ PRO_VIR_DIR }}" --shell=/bin/false --stdin

- name: ftpgroup
  shell: ftpasswd --file=/usr/local/etc/proftpd/group --group --name="{{ PRO_GROUP_NAME }}" --gid="{{ PRO_GID }}"

- name: Add ftpuser to ftpgroup
  shell: ftpasswd --group --name="{{ PRO_GROUP_NAME }}" --gid="{{ PRO_GID }}" --member="{{ PRO_VIRTUAL_USER }}" --file=/usr/local/etc/proftpd/group

- name: Create ProFTPD configuration file
  template: src=proftpd.conf dest=/etc/proftpd/proftpd.conf backup=yes
  notify:
  - restart proftpd

- name: Start ProFTPD Service
  service: name=proftpd state=started enabled=yes
